"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.langPostsRouter = void 0;
var express = require('express');
var controller = require("../controllers/langPost.controller");
exports.langPostsRouter = express();
exports.langPostsRouter.get('/lang/posts', controller.getPosts);
exports.langPostsRouter.post('/lang/posts/createpost', controller.createPost);
exports.langPostsRouter.get('/lang/posts/:id', controller.getSinglePost);
exports.langPostsRouter.patch('/lang/posts/:id', controller.updatePost);
exports.langPostsRouter.delete('/lang/posts/:id', controller.deletePost);
exports.langPostsRouter.post('/lang/posts/:id', controller.togglePostLike);
exports.langPostsRouter.post('/lang/comments/createcomment/:id', controller.createComment);
exports.langPostsRouter.get('/lang/comments/:id', controller.getComments);
exports.langPostsRouter.patch('/lang/comments/:commentindex', controller.updateComment);
exports.langPostsRouter.delete('/lang/comments/:commentindex', controller.deleteComment);
